#!/usr/bin/env bash
# Usage: cli build [--cli]
# Summary: Build the sdk
# Help: Build the sdk

set -e

cd "$_CLI_ROOT/../../"

if [ -z $1 ]; then
    xcodebuild -configuration Release -scheme Analytics -workspace Analytics.xcworkspace
    xcodebuild -configuration Release -scheme Analytics.framework -workspace Analytics.xcworkspace
else
  ./scripts/tests/test_headers.rb && xcodebuild -sdk iphonesimulator -workspace Analytics.xcworkspace/ -destination "platform=iOS Simulator,name=iPhone Retina (4-inch)" -scheme 'iOS Tests' clean test
fi
