#!/usr/bin/env bash
# Usage: cli var <var>
# Summary: Get the build setting var
# Help: Get the build setting var

set -e

cd "$_CLI_ROOT/../../"

xcodebuild -showBuildSettings -configuration Release -scheme Analytics.framework -workspace Analytics.xcworkspace | grep "$1 =" | cut -d= -f2 | sed -e 's/^ *//' -e 's/ *$//'

