#!/usr/bin/env node

var knox = require('knox');
var conf = require('s-config');
var fs = require('fs');
var program = require('commander');
var client = knox.createClient(conf('s3'));
var path = require('path');

program
  .option('-p, --path <path>', 'The path to the sdk zip to upload to s3')
  .parse(process.argv);

var folder = '/releases/ios';
var dest = path.join(folder, path.basename(program.path));

client.putFile(program.path, dest, { 'x-amz-acl': 'public-read' }, function (err, res) {
  if (err || res.statusCode != 200)
    throw err;
  console.log('Uploaded ' + program.path + ' to ' + dest + ' on s3');
});
