use_frameworks!

target 'Analytics_Example' do
  pod 'Analytics', :path => '../'

  target 'Analytics_Tests' do
    use_frameworks!
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'Nocilla'
    pod 'Quick' # runner lib
    pod 'Nimble' # Matcher lib
    pod 'Mockingjay'

  end
end
