#!/usr/bin/env bash

version="$1"

if [ -z "$version" ]; then
    echo "Version needs to be given in the form x.x.x. E.g. $ release 1.7.4"
    exit
fi

set_version_number () {
  sed -i '' "s/ANALYTICS_VERSION =.*;/ANALYTICS_VERSION = $version;/" Analytics.xcodeproj/project.pbxproj
}

get_var () {
  xcodebuild -showBuildSettings -configuration Release -scheme Analytics.framework -workspace Analytics.xcworkspace | grep "$1 =" | cut -d= -f2 | sed -e 's/^ *//' -e 's/ *$//'
}

build_framework () {
    xcodebuild -configuration Release -scheme Analytics.framework -workspace Analytics.xcworkspace
}

upload_to_s3 () {
  "$(get_var SRCROOT)/scripts/upload-to-s3" --path "$(get_var SYMROOT)/Release/Analytics-$1.zip"
}

set_version_number

build_framework

git add --all
git commit -m "Release $version"
git tag "$version"
git push --follow-tags origin master

# push to s3
upload_to_s3 "$version"
upload_to_s3 "latest-stable"

# push to cocoapods
pod trunk push "$(get_var SRCROOT)/Analytics.podspec"
